descriptor-schema-version: 2.0
 
info:
  name: "IOTEventNotification"
  description: "Notification Engine for events"
  version: "1.0"
  author-link: "https://github.com/imapex/IOTEventNotification"
  author-name: "Chris Bogdon cbogdon@cisco.com"
 
app:
  type: paas

  resources:
    profile: c1.small
 
    network:
      - 
        interface-name: eth0
        ports: 
            tcp: [9000]

# Specify runtime and startup
  startup:
    runtime: python 
    runtime-version: 2.7
    target: IOTEventNotification.py
