descriptor-schema-version: 2.0
 
info:
  name: "TellerEye"
  description: "Notify Teller of drive-thru customer"
  version: "0.1"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"
 
app:
  type: paas

  resources:
    profile: c1.small
 
    network:
      - 
        interface-name: eth0
        ports: 
            tcp: [9000]

# Specify runtime and startup
  startup:
    runtime: python 
    runtime-version: 2.7
    target: IOTEventNotification.py
